db:
  # container_name: fu_mongo
  #hostname: fu_mongo
  log_driver: "none"
  image: mongo:3
  entrypoint: [ "mongod", "--smallfiles", "--rest" ]
  expose:
    - "27017"

redis:
  # container_name: fu_redis
  #hostname: fu_redis
  log_driver: "none"
  image: redis
  expose:
    - "6379"

web:
  build: .
  command: npm test
  volumes:
    - ./coverage:/usr/src/app/coverage
  environment:
    USE_LOCAL_REPO: 'true'
    PORT: 9000
    MONGODB_URL: 'mongodb://db:27017/fuse-features-api'
    MONGODB_OPLOG: 'mongodb://db:27017/local'
    REDIS_HOST: 'redis'
    REDIS_PORT: 6379
    NODE_ENV: 'dev'
    FEATURE_RELEASES_DATES: "nov/15,mar/16,nov/16"
    NPM_CONFIG_PRODUCTION: 'false'
  links:
    - db
    - redis
